
services:
  postgres: 
    image: postgres:16-alpine
    container_name: experienceclub_postgres
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      #- ~/postgres:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}  

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: experienceclub_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@experienceclub.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      # This file pre-configures the database connection for pgAdmin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
      - pgadmin:/var/lib/pgadmin/data
    ports:
      - "${PGADMIN_PORT}:80"
    # This ensures pgAdmin can connect to the 'postgres' service from your main docker-compose.yml
    # It assumes the default network is named 'experienceclub-full_default'
    networks:
      - default

volumes:
  postgres:
    name: server-db-postgres
  pgadmin:
    name: server-db-pgadmin